apiVersion: v1
kind: Service
metadata:
  name: greeting-svc
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: greeting
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: greeting
  # pod
  template:
    metadata:
      labels:
        app: greeting
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: greeting
          image: registry.cn-hangzhou.aliyuncs.com/xvrzhao/greeting-server
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - containerPort: 8080
