apiVersion: v1
kind: Pod
metadata:
  name: greeting-client
  namespace: default
spec:
  containers:
    - name: greeting-client
      image: xvrzhao/greeting-client

---

apiVersion: v1
kind: Service
metadata:
  name: greeting-svc
  namespace: default
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: greeting
  ports:
    - protocol: TCP
      port: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting-deploy
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: greeting
  template:
    metadata:
      labels:
        app: greeting
    spec:
      containers:
        - name: greeting
          image: xvrzhao/greeting-server
          ports:
            - containerPort: 8080